- name: Hello world
  # hosts: web
  hosts: local
  connection: local
  tasks:
    - name: print hello world
      ansible.builtin.debug:
        msg: "Hello Wrold"
- name: Hello world from play2
  hosts: local
  connection: local
  tasks:
    - name: print play 2
      ansible.builtin.debug:
        msg: "Hello world from play2"